version: '3.3'
services:
  mongodb:
    container_name: mongo
    image: mongo
    ports:
     - 27017:27017
    volumes:
        - my-mongo-volume:/data/db
    networks: 
     - java-mongo-network
      
  starwars:    
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
     - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/starWars
    ports:
     - 8080:8080
    networks: 
     - java-mongo-network
    depends_on:
     - mongodb
    
volumes:
  my-mongo-volume:

networks: 
  java-mongo-network:
    driver: bridge


