server:
  servlet:
    context-path: /starWars
  port: 8080 
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/starwars
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration